version: '3'

services:
    app:
        image: gwas-streamlit-docker
        deploy:
          resources:
            limits:
              cpus: 2
              memory: 768M
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT=8080
        ports:
            - 8080:8080
        volumes:
            - ./app:/usr/app/src/